import { useState, useRef, useEffect } from "react";

// ─── DESIGN TOKENS ────────────────────────────────────────────────────────────
const T = {
  teal:      "#1A4D5C",
  tealMid:   "#256478",
  tealLight: "#3A8FA3",
  saffron:   "#E8871A",
  saffronLight: "#F5A94E",
  ivory:     "#F7F4EF",
  ivoryDark: "#EDE8E0",
  slate:     "#3D4F56",
  slateLight:"#7A9199",
  white:     "#FFFFFF",
  red:       "#C0392B",
  green:     "#1E7E44",
  greenLight:"#D4EDDA",
};

// ─── CONFIG — FILL THESE IN ───────────────────────────────────────────────────
const CONFIG = {
  SPREADSHEET_ID: "1odcykU6dYGkfpfywM6zGhJzJ-O5IJhZvmC-VE5pPn30",
  CLIENT_ID:      "495720211481-69rv0h93ajenbo2plau0d94bkujr7a4q.apps.googleusercontent.com",
  SCOPES:         "https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/drive.file",
  DRIVE_FOLDER_ID:"1S8DJLtsxIGXwzAVRHbLZjGASeL0hKhvu"
};

const SHEETS = {
  MEMBERS:      "Members",
  CHEQUES:      "Cheque_Payments",
  WITHDRAWALS:  "Cash_Withdrawals",
  EXPENSES:     "Expenses",
};

const SHEET_HEADERS = {
  Members:          ["Flat No","Wing","Owner Name","Mobile","Email","Active"],
  Cheque_Payments:  ["Timestamp","Wing","Flat No","Member Name","Mobile","Cheque No","Bank Name","Amount","Cheque Date","Image Link","Recorded By"],
  Cash_Withdrawals: ["Timestamp","Member Name","Amount","Date","Purpose / Remarks","Recorded By","Reference ID"],
  Expenses:         ["Timestamp","Category","Sub-Category / Vendor","Amount","Payment Mode","Cheque No","Bank Name","Cheque Date","Withdrawn By","Spent By","Withdrawal Ref ID","Invoice Link","Notes","Recorded By"],
  Petty_Cash_Summary:["Summary Date","Total Withdrawn","Total Spent (Cash)","Available Balance","Generated By"],
};

// ─── GLOBAL STYLES ────────────────────────────────────────────────────────────
const globalCSS = `
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Poppins:wght@600;700&display=swap');
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Inter', sans-serif; background: #F7F4EF; color: #3D4F56; min-height: 100vh; }

  .portal-header {
    background: linear-gradient(135deg, #1A4D5C 0%, #256478 60%, #3A8FA3 100%);
    position: sticky; top: 0; z-index: 100;
    box-shadow: 0 2px 12px rgba(26,77,92,0.3);
  }
  .header-top { display:flex; align-items:center; gap:16px; padding:14px 24px 10px; }
  .header-logo { width:46px; height:46px; background:#E8871A; border-radius:10px; display:flex; align-items:center; justify-content:center; font-size:22px; flex-shrink:0; }
  .header-title { font-family:'Poppins',sans-serif; font-size:17px; font-weight:700; color:#fff; line-height:1.2; }
  .header-sub { font-size:11px; color:rgba(255,255,255,0.7); margin-top:2px; }
  .header-auth { margin-left:auto; display:flex; align-items:center; gap:10px; }
  .auth-badge { font-size:12px; color:rgba(255,255,255,0.85); background:rgba(255,255,255,0.12); padding:4px 10px; border-radius:20px; }
  .btn-auth { background:#E8871A; color:white; border:none; padding:7px 16px; border-radius:8px; font-size:13px; font-weight:600; cursor:pointer; }
  .btn-auth:hover { background:#F5A94E; }
  .btn-auth:disabled { background:#7A9199; cursor:not-allowed; }

  .nav-tabs { display:flex; gap:2px; padding:0 16px; overflow-x:auto; scrollbar-width:none; }
  .nav-tabs::-webkit-scrollbar { display:none; }
  .nav-tab { padding:10px 18px; font-size:13px; font-weight:500; color:rgba(255,255,255,0.65); border:none; background:transparent; cursor:pointer; border-bottom:3px solid transparent; white-space:nowrap; transition:all 0.2s; display:flex; align-items:center; gap:6px; }
  .nav-tab:hover { color:rgba(255,255,255,0.9); }
  .nav-tab.active { color:#fff; border-bottom-color:#E8871A; font-weight:600; }

  .page { max-width:860px; margin:28px auto; padding:0 16px 60px; }
  .page-title { font-family:'Poppins',sans-serif; font-size:22px; font-weight:700; color:#1A4D5C; margin-bottom:4px; }
  .page-desc { font-size:13px; color:#7A9199; margin-bottom:24px; }

  .card { background:#fff; border-radius:14px; padding:24px; box-shadow:0 2px 8px rgba(26,77,92,0.08); margin-bottom:20px; }
  .card-title { font-size:15px; font-weight:600; color:#1A4D5C; margin-bottom:18px; padding-bottom:10px; border-bottom:2px solid #EDE8E0; display:flex; align-items:center; gap:8px; }

  .form-grid { display:grid; grid-template-columns:1fr 1fr; gap:16px; }
  .form-grid.cols-3 { grid-template-columns:1fr 1fr 1fr; }
  @media(max-width:700px){ .form-grid.cols-3 { grid-template-columns:1fr 1fr; } }
  @media(max-width:580px){ .form-grid, .form-grid.cols-3 { grid-template-columns:1fr; } }

  .field { display:flex; flex-direction:column; gap:5px; }
  .field.full { grid-column:1 / -1; }
  label { font-size:12px; font-weight:600; color:#3D4F56; text-transform:uppercase; letter-spacing:0.4px; }
  input, select, textarea { border:1.5px solid #EDE8E0; border-radius:8px; padding:9px 12px; font-size:14px; font-family:'Inter',sans-serif; color:#3D4F56; background:#F7F4EF; transition:border-color 0.2s,box-shadow 0.2s; outline:none; width:100%; }
  input:focus, select:focus, textarea:focus { border-color:#3A8FA3; box-shadow:0 0 0 3px rgba(58,143,163,0.12); background:#fff; }
  input[readonly] { background:#EDE8E0; cursor:default; }

  .btn { padding:11px 24px; border-radius:9px; font-size:14px; font-weight:600; border:none; cursor:pointer; transition:all 0.2s; display:inline-flex; align-items:center; gap:7px; }
  .btn-primary { background:#1A4D5C; color:white; }
  .btn-primary:hover { background:#256478; transform:translateY(-1px); box-shadow:0 4px 12px rgba(26,77,92,0.25); }
  .btn-primary:disabled { background:#7A9199; cursor:not-allowed; transform:none; box-shadow:none; }
  .btn-secondary { background:#EDE8E0; color:#3D4F56; }
  .btn-secondary:hover { background:#ddd5c8; }
  .btn-mode { flex:1; justify-content:center; }
  .btn-mode.active-cash { background:#E8871A; color:white; }
  .btn-mode.active-cheque { background:#1A4D5C; color:white; }

  .form-actions { margin-top:22px; display:flex; gap:10px; justify-content:flex-end; }

  .alert { padding:12px 16px; border-radius:9px; font-size:13px; font-weight:500; margin-bottom:18px; display:flex; align-items:center; gap:8px; }
  .alert-success { background:#D4EDDA; color:#1E7E44; border:1px solid #a8d5b5; }
  .alert-error   { background:#fde8e6; color:#C0392B; border:1px solid #f5b7b1; }
  .alert-info    { background:#e8f4f8; color:#1A4D5C; border:1px solid #b0d9e8; }
  .alert-warn    { background:#fff3e0; color:#b45309; border:1px solid #fcd38a; }

  .img-capture-area { border:2px dashed #3A8FA3; border-radius:10px; padding:20px; text-align:center; background:#f0f9fc; cursor:pointer; transition:background 0.2s; }
  .img-capture-area:hover { background:#e0f4f8; }
  .img-preview { width:100%; max-height:160px; object-fit:contain; border-radius:8px; margin-top:10px; border:1px solid #EDE8E0; }

  .setup-step { display:flex; gap:14px; margin-bottom:18px; align-items:flex-start; }
  .step-num { width:28px; height:28px; background:#1A4D5C; color:white; border-radius:50%; display:flex; align-items:center; justify-content:center; font-size:13px; font-weight:700; flex-shrink:0; margin-top:2px; }
  .step-title { font-weight:600; font-size:14px; color:#1A4D5C; margin-bottom:4px; }
  .step-desc { font-size:13px; color:#3D4F56; line-height:1.6; }

  .header-pill { display:inline-block; background:#1A4D5C; color:white; font-size:11px; padding:2px 8px; border-radius:4px; margin:2px; font-family:monospace; }
  .sheet-headers-grid { display:flex; flex-wrap:wrap; gap:6px; margin-top:8px; }

  .config-warning { background:linear-gradient(135deg,#fff3e0,#fff8ed); border:2px solid #E8871A; border-radius:12px; padding:20px 22px; margin-bottom:24px; }
  .config-warning h3 { color:#b45309; font-size:15px; margin-bottom:8px; }
  .config-warning p { font-size:13px; color:#7c5012; line-height:1.6; }

  .spinner { width:18px; height:18px; border:2px solid rgba(255,255,255,0.4); border-top-color:white; border-radius:50%; animation:spin 0.7s linear infinite; display:inline-block; }
  @keyframes spin { to { transform:rotate(360deg); } }

  .records-table { width:100%; border-collapse:collapse; font-size:13px; }
  .records-table th { background:#1A4D5C; color:white; padding:10px 12px; text-align:left; font-weight:600; font-size:12px; }
  .records-table td { padding:9px 12px; border-bottom:1px solid #EDE8E0; color:#3D4F56; }
  .records-table tr:hover td { background:#f0f9fc; }
  .records-table tr:last-child td { border-bottom:none; }

  .tag { display:inline-block; padding:2px 8px; border-radius:4px; font-size:11px; font-weight:600; }
  .tag-cheque { background:#e8f4f8; color:#1A4D5C; }
  .tag-cash   { background:#fff3e0; color:#b45309; }

  /* Petty Cash Tracker summary cards */
  .summary-cards { display:flex; gap:14px; margin-bottom:20px; flex-wrap:wrap; }
  .summary-card  { background:#fff; border-radius:12px; padding:18px 20px; box-shadow:0 2px 8px rgba(26,77,92,0.08); flex:1; min-width:160px; }

  /* View Records table scrollable container */
  .records-scroll { overflow-x:auto; border-radius:0 0 14px 14px; }

  /* Spinner variant for light bg */
  .spinner-dark { width:16px; height:16px; border:2px solid #ccc; border-top-color:#3D4F56; border-radius:50%; animation:spin 0.7s linear infinite; display:inline-block; }

  /* Sign out button */
  .btn-signout { background:rgba(255,255,255,0.15); color:white; border:1px solid rgba(255,255,255,0.3); padding:6px 14px; border-radius:8px; font-size:12px; cursor:pointer; }
  .btn-signout:hover { background:rgba(255,255,255,0.25); }
`;

// ─── UTILITIES ────────────────────────────────────────────────────────────────
function generateRefId() { return "REF-" + Date.now().toString(36).toUpperCase(); }
function today() { return new Date().toISOString().split("T")[0]; }
function nowTs() { return new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }); }

function compressImage(file, maxW = 800, quality = 0.55) {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement("canvas");
        let w = img.width, h = img.height;
        if (w > maxW) { h = (h * maxW) / w; w = maxW; }
        canvas.width = w; canvas.height = h;
        canvas.getContext("2d").drawImage(img, 0, 0, w, h);
        canvas.toBlob((blob) => resolve(blob), "image/jpeg", quality);
      };
      img.src = e.target.result;
    };
    reader.readAsDataURL(file);
  });
}

// ─── GOOGLE API HELPERS ───────────────────────────────────────────────────────
async function appendToSheet(sheetName, rowData, token) {
  const url = `https://sheets.googleapis.com/v4/spreadsheets/${CONFIG.SPREADSHEET_ID}/values/${encodeURIComponent(sheetName + "!A1")}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`;
  const resp = await fetch(url, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({ values: [rowData] }),
  });
  if (!resp.ok) throw new Error(await resp.text());
  return resp.json();
}

async function readSheet(sheetName, token) {
  const url = `https://sheets.googleapis.com/v4/spreadsheets/${CONFIG.SPREADSHEET_ID}/values/${encodeURIComponent(sheetName + "!A2:Z500")}`;
  const resp = await fetch(url, { headers: { Authorization: `Bearer ${token}` } });
  if (!resp.ok) throw new Error(await resp.text());
  const data = await resp.json();
  return data.values || [];
}

async function writeSheetHeaders(sheetName, headers, token) {
  const url = `https://sheets.googleapis.com/v4/spreadsheets/${CONFIG.SPREADSHEET_ID}/values/${encodeURIComponent(sheetName + "!A1")}?valueInputOption=RAW`;
  const resp = await fetch(url, {
    method: "PUT",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({ values: [headers] }),
  });
  if (!resp.ok) throw new Error(await resp.text());
  return resp.json();
}

async function uploadToDrive(blob, fileName, token) {
  const meta = JSON.stringify({ name: fileName, parents: [CONFIG.DRIVE_FOLDER_ID] });
  const form = new FormData();
  form.append("metadata", new Blob([meta], { type: "application/json" }));
  form.append("file", blob, fileName);
  const resp = await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink", {
    method: "POST",
    headers: { Authorization: `Bearer ${token}` },
    body: form,
  });
  if (!resp.ok) throw new Error(await resp.text());
  const data = await resp.json();
  await fetch(`https://www.googleapis.com/drive/v3/files/${data.id}/permissions`, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({ role: "reader", type: "anyone" }),
  });
  return data.webViewLink;
}

// ─── SHARED COMPONENTS ────────────────────────────────────────────────────────
function Alert({ type, children, onClose }) {
  if (!children) return null;
  const icons = { success: "✅", error: "❌", warn: "⚠️", info: "ℹ️" };
  return (
    <div className={`alert alert-${type}`}>
      <span>{icons[type]}</span>
      <span style={{ flex: 1 }}>{children}</span>
      {onClose && <span onClick={onClose} style={{ cursor: "pointer", marginLeft: 8, opacity: 0.6 }}>✕</span>}
    </div>
  );
}

function ImageCapture({ label, onCapture, preview }) {
  const cameraRef = useRef();
  const uploadRef = useRef();

  async function handleFile(e) {
    const file = e.target.files[0];
    if (!file) return;
    const blob = await compressImage(file);
    onCapture(blob, URL.createObjectURL(blob));
  }

  return (
    <div className="field full">
      {label && <label>{label}</label>}
      {preview
        ? <div>
            <img src={preview} className="img-preview" alt="preview"
              style={{ display:"block", width:"100%", maxHeight:200, objectFit:"contain", borderRadius:10, border:"1.5px solid #EDE8E0" }} />
            <button className="btn btn-secondary" style={{ marginTop:8, fontSize:12, padding:"5px 14px" }}
              onClick={() => { onCapture(null, null); cameraRef.current.value=""; uploadRef.current.value=""; }}>
              ✕ Remove Image
            </button>
          </div>
        : <div className="img-capture-area">
            <div style={{ fontSize:28, marginBottom:8 }}>🖼️</div>
            <div style={{ fontSize:13, color:"#3D4F56", fontWeight:500, marginBottom:12 }}>Attach image or document</div>
            <div style={{ display:"flex", gap:10, justifyContent:"center", flexWrap:"wrap" }}>
              <button className="btn btn-primary" style={{ fontSize:13, padding:"8px 18px" }}
                onClick={() => cameraRef.current.click()}>
                📷 Take Photo
              </button>
              <button className="btn btn-secondary" style={{ fontSize:13, padding:"8px 18px" }}
                onClick={() => uploadRef.current.click()}>
                📁 Upload from Device
              </button>
            </div>
            <div style={{ fontSize:11, color:"#7A9199", marginTop:10 }}>JPG, PNG or PDF · Auto-compressed · Saved to Google Drive</div>
          </div>
      }
      <input ref={cameraRef} type="file" accept="image/*" capture="environment" style={{ display:"none" }} onChange={handleFile} />
      <input ref={uploadRef} type="file" accept="image/*,application/pdf" style={{ display:"none" }} onChange={handleFile} />
    </div>
  );
}

// ─── SETUP GUIDE ─────────────────────────────────────────────────────────────
function SetupGuide({ token, onHeadersWritten }) {
  const [writing, setWriting] = useState(false);
  const [done, setDone] = useState({});
  const [msg, setMsg] = useState(null);
  const isConfigured = CONFIG.SPREADSHEET_ID !== "YOUR_SPREADSHEET_ID_HERE";

  async function writeAllHeaders() {
    if (!token) { setMsg({ type: "error", text: "Please sign in with Google first." }); return; }
    setWriting(true); setMsg(null);
    const results = {};
    for (const [sheet, headers] of Object.entries(SHEET_HEADERS)) {
      try { await writeSheetHeaders(sheet, headers, token); results[sheet] = "✅ Done"; }
      catch (e) { results[sheet] = "❌ " + e.message; }
    }
    setDone(results); setWriting(false);
    setMsg({ type: "success", text: "All headers written to Google Sheets!" });
    if (onHeadersWritten) onHeadersWritten();
  }

  const steps = [
    { title: "Create a Google Cloud Project", desc: <>Go to <strong>console.cloud.google.com</strong> → New Project → Name it "Shubh Nisarg Portal". Enable <em>Google Sheets API v4</em> and <em>Google Drive API</em>.</> },
    { title: "Create OAuth 2.0 Credentials", desc: <>APIs & Services → Credentials → Create Credentials → OAuth 2.0 Client ID → Web Application. Add your portal URL to "Authorised JavaScript Origins". Copy the <strong>Client ID</strong> into CONFIG.CLIENT_ID in the code.</> },
    { title: "Get your Spreadsheet ID", desc: <>Open your Google Sheet. Copy the ID from the URL: <code style={{background:"#EDE8E0",padding:"1px 5px",borderRadius:4}}>docs.google.com/spreadsheets/d/<strong>COPY_THIS</strong>/edit</code>. Paste it into <strong>CONFIG.SPREADSHEET_ID</strong>.</> },
    { title: "Create a Drive Folder for Images", desc: <>In Google Drive, create a folder "Shubh Nisarg CHS Images". Copy its ID from the URL and set it as <strong>CONFIG.DRIVE_FOLDER_ID</strong>.</> },
    { title: "Sign in & Write Sheet Headers", desc: "Click Sign in with Google above, then click the button below to automatically write all column headers to every sheet in your workbook." },
  ];

  return (
    <div>
      <div className="page-title">⚙️ Setup Guide</div>
      <div className="page-desc">Follow these one-time steps to connect the portal to your Google Sheet.</div>

      {!isConfigured && (
        <div className="config-warning">
          <h3>🔧 One-time Configuration Required</h3>
          <p>Open this file's source code and fill in the <strong>CONFIG</strong> block at the top (lines 13–17) with your Google credentials. The steps below guide you through getting each value.</p>
        </div>
      )}

      <div className="card">
        <div className="card-title">📋 Step-by-Step Setup</div>
        {steps.map((s, i) => (
          <div className="setup-step" key={i}>
            <div className="step-num">{i + 1}</div>
            <div>
              <div className="step-title">{s.title}</div>
              <div className="step-desc">{s.desc}</div>
            </div>
          </div>
        ))}
        {msg && <Alert type={msg.type}>{msg.text}</Alert>}
        <button className="btn btn-primary" onClick={writeAllHeaders} disabled={writing || !isConfigured}>
          {writing ? <><span className="spinner" /> Writing Headers…</> : "📝 Write All Headers to Google Sheets"}
        </button>
        {Object.keys(done).length > 0 && (
          <div style={{ marginTop: 14 }}>
            {Object.entries(done).map(([sheet, status]) => (
              <div key={sheet} style={{ fontSize: 13, marginBottom: 4 }}><strong>{sheet}</strong>: {status}</div>
            ))}
          </div>
        )}
      </div>

      <div className="card">
        <div className="card-title">📊 Column Headers Reference</div>
        <div style={{ fontSize: 12, color: "#7A9199", marginBottom: 14 }}>These will be written to your Google Sheet automatically when you click the button above.</div>
        {Object.entries(SHEET_HEADERS).map(([sheet, cols]) => (
          <div key={sheet} style={{ marginBottom: 20 }}>
            <div style={{ fontSize: 13, fontWeight: 600, color: "#1A4D5C", marginBottom: 6 }}>📄 {sheet}</div>
            <div className="sheet-headers-grid">{cols.map((c, i) => <span key={i} className="header-pill">{c}</span>)}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── CHEQUE PAYMENT ───────────────────────────────────────────────────────────
// Note: Cheque payments are open to ALL society members (not just committee).
// Name and mobile are free-text — no dropdown restriction.
function ChequePayment({ token, currentUser }) {
  const empty = { wing: "", flat: "", name: "", mobile: "", chequeNo: "", bank: "", amount: "", chequeDate: today() };
  const [form, setForm] = useState(empty);
  const [imgBlob, setImgBlob] = useState(null);
  const [imgPreview, setImgPreview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [msg, setMsg] = useState(null);
  const [records, setRecords] = useState([]);

  const WINGS = ["A","B","C","D","E","F"];
  const BANKS = ["State Bank of India","Bank of Maharashtra","HDFC Bank","ICICI Bank","Axis Bank","Punjab National Bank","Canara Bank","Union Bank","Bank of Baroda","Kotak Mahindra Bank","Other"];

  function set(k, v) { setForm(f => ({ ...f, [k]: v })); }

  async function handleSubmit() {
    if (!form.wing || !form.flat || !form.name || !form.chequeNo || !form.bank || !form.amount || !form.chequeDate) {
      setMsg({ type: "error", text: "Please fill all required fields (marked with *)." }); return;
    }
    if (!/^\d{10}$/.test(form.mobile) && form.mobile !== "") {
      setMsg({ type: "error", text: "Mobile number must be 10 digits if provided." }); return;
    }
    if (!token) { setMsg({ type: "error", text: "Please sign in first." }); return; }
    setLoading(true); setMsg(null);
    try {
      let imageLink = "";
      if (imgBlob) {
        const fname = `Cheque_${form.chequeNo}_${form.name.replace(/\s+/g,"_")}_${Date.now()}.jpg`;
        imageLink = await uploadToDrive(imgBlob, fname, token);
      }
      await appendToSheet(SHEETS.CHEQUES, [nowTs(), form.wing, form.flat, form.name, form.mobile, form.chequeNo, form.bank, form.amount, form.chequeDate, imageLink, currentUser], token);
      setRecords(r => [{ ...form, imageLink }, ...r.slice(0, 4)]);
      setMsg({ type: "success", text: `✅ Cheque #${form.chequeNo} from ${form.name} saved!` });
      setForm(empty); setImgBlob(null); setImgPreview(null);
    } catch (e) { setMsg({ type: "error", text: "Error: " + e.message }); }
    setLoading(false);
  }

  return (
    <div>
      <div className="page-title">🏦 Cheque Payment Entry</div>
      <div className="page-desc">Record cheques received from any society member toward maintenance or other dues.</div>
      <div className="alert alert-info" style={{ marginBottom: 18 }}>
        <span>ℹ️</span>
        <span>This form is open to <strong>all society members</strong>. Enter name and mobile manually — no committee restriction applies here.</span>
      </div>
      {msg && <Alert type={msg.type} onClose={() => setMsg(null)}>{msg.text}</Alert>}

      <div className="card">
        <div className="card-title">👤 Member Details</div>
        <div className="form-grid">
          <div className="field">
            <label>Member Name *</label>
            <input value={form.name} onChange={e => set("name", e.target.value)} placeholder="Full name of flat owner" />
          </div>
          <div className="field">
            <label>Mobile Number</label>
            <input value={form.mobile} onChange={e => set("mobile", e.target.value.replace(/\D/g,"").slice(0,10))}
              placeholder="10-digit mobile number" maxLength={10} inputMode="numeric" />
          </div>
          <div className="field">
            <label>Wing *</label>
            <select value={form.wing} onChange={e => set("wing", e.target.value)}>
              <option value="">— Wing —</option>
              {WINGS.map(w => <option key={w} value={w}>Wing {w}</option>)}
            </select>
          </div>
          <div className="field">
            <label>Flat Number *</label>
            <input value={form.flat} onChange={e => set("flat", e.target.value)} placeholder="e.g. 101, 204B" />
          </div>
        </div>
      </div>

      <div className="card">
        <div className="card-title">🧾 Cheque Details</div>
        <div className="form-grid cols-3">
          <div className="field">
            <label>Cheque Number *</label>
            <input value={form.chequeNo} onChange={e => set("chequeNo", e.target.value)} placeholder="000123" />
          </div>
          <div className="field">
            <label>Bank *</label>
            <select value={form.bank} onChange={e => set("bank", e.target.value)}>
              <option value="">— Select Bank —</option>
              {BANKS.map(b => <option key={b} value={b}>{b}</option>)}
            </select>
          </div>
          <div className="field">
            <label>Cheque Date *</label>
            <input type="date" value={form.chequeDate} onChange={e => set("chequeDate", e.target.value)} />
          </div>
          <div className="field">
            <label>Amount (₹) *</label>
            <input type="number" value={form.amount} onChange={e => set("amount", e.target.value)} placeholder="0.00" min="0" />
          </div>
        </div>
        <div style={{ marginTop: 18 }}>
          <ImageCapture label="Cheque Image (optional — compressed & uploaded to Google Drive)" preview={imgPreview} onCapture={(b, u) => { setImgBlob(b); setImgPreview(u); }} />
        </div>
        <div className="form-actions">
          <button className="btn btn-secondary" onClick={() => { setForm(empty); setImgBlob(null); setImgPreview(null); setMsg(null); }}>Clear</button>
          <button className="btn btn-primary" onClick={handleSubmit} disabled={loading}>
            {loading ? <><span className="spinner" /> Saving…</> : "💾 Save Cheque Entry"}
          </button>
        </div>
      </div>

      {records.length > 0 && (
        <div className="card">
          <div className="card-title">🕐 Recently Added (this session)</div>
          <div style={{ overflowX: "auto" }}>
            <table className="records-table">
              <thead><tr><th>Member</th><th>Wing/Flat</th><th>Cheque No</th><th>Bank</th><th>Amount</th><th>Date</th></tr></thead>
              <tbody>
                {records.map((r, i) => (
                  <tr key={i}>
                    <td>{r.name}</td><td>{r.wing}-{r.flat}</td><td><code>{r.chequeNo}</code></td>
                    <td style={{fontSize:12}}>{r.bank}</td>
                    <td><strong>₹{Number(r.amount).toLocaleString("en-IN")}</strong></td>
                    <td>{r.chequeDate}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── CASH WITHDRAWAL ──────────────────────────────────────────────────────────
function CashWithdrawal({ token, members, currentUser }) {
  const empty = { name: "", amount: "", date: today(), purpose: "" };
  const [form, setForm] = useState(empty);
  const [loading, setLoading] = useState(false);
  const [msg, setMsg] = useState(null);
  const [records, setRecords] = useState([]);
  function set(k, v) { setForm(f => ({ ...f, [k]: v })); }

  const PURPOSES = ["Daily maintenance materials","Emergency repairs","Stationery & office supplies","Vendor advance","Meeting refreshments","Postage / courier","Garden / horticulture","Miscellaneous","Other"];

  async function handleSubmit() {
    if (!form.name || !form.amount || !form.date) { setMsg({ type: "error", text: "Member name, amount and date are required." }); return; }
    if (!token) { setMsg({ type: "error", text: "Please sign in first." }); return; }
    setLoading(true); setMsg(null);
    const refId = generateRefId();
    try {
      await appendToSheet(SHEETS.WITHDRAWALS, [nowTs(), form.name, form.amount, form.date, form.purpose, currentUser, refId], token);
      setRecords(r => [{ ...form, refId }, ...r.slice(0, 4)]);
      setMsg({ type: "success", text: `₹${Number(form.amount).toLocaleString("en-IN")} withdrawal recorded for ${form.name}. Ref: ${refId}` });
      setForm(empty);
    } catch (e) { setMsg({ type: "error", text: "Error: " + e.message }); }
    setLoading(false);
  }

  return (
    <div>
      <div className="page-title">💵 Cash Withdrawal</div>
      <div className="page-desc">Record petty cash handed out to authorised committee members only.</div>
      <div className="alert alert-warn" style={{ marginBottom: 18 }}>
        <span>⚠️</span>
        <span><strong>Committee members only.</strong> Only registered committee members appear in this dropdown. Add members in the Committee tab first.</span>
      </div>
      {msg && <Alert type={msg.type} onClose={() => setMsg(null)}>{msg.text}</Alert>}

      <div className="card">
        <div className="card-title">📋 Withdrawal Details</div>
        <div className="form-grid">
          <div className="field">
            <label>Member Name *</label>
            <select value={form.name} onChange={e => set("name", e.target.value)}>
              <option value="">— Select Member —</option>
              {members.map((m, i) => <option key={i} value={m[2]}>{m[2]}</option>)}
            </select>
          </div>
          <div className="field">
            <label>Withdrawal Date *</label>
            <input type="date" value={form.date} onChange={e => set("date", e.target.value)} />
          </div>
          <div className="field">
            <label>Amount (₹) *</label>
            <input type="number" value={form.amount} onChange={e => set("amount", e.target.value)} placeholder="0.00" min="0" />
          </div>
          <div className="field">
            <label>Purpose / Remarks</label>
            <select value={form.purpose} onChange={e => set("purpose", e.target.value)}>
              <option value="">— Select Purpose —</option>
              {PURPOSES.map(p => <option key={p} value={p}>{p}</option>)}
            </select>
          </div>
        </div>
        <div className="form-actions">
          <button className="btn btn-secondary" onClick={() => { setForm(empty); setMsg(null); }}>Clear</button>
          <button className="btn btn-primary" onClick={handleSubmit} disabled={loading}>
            {loading ? <><span className="spinner" /> Recording…</> : "💾 Record Withdrawal"}
          </button>
        </div>
      </div>

      {records.length > 0 && (
        <div className="card">
          <div className="card-title">🕐 Recently Added (this session)</div>
          <div style={{ overflowX: "auto" }}>
            <table className="records-table">
              <thead><tr><th>Member</th><th>Amount</th><th>Date</th><th>Purpose</th><th>Reference ID</th></tr></thead>
              <tbody>
                {records.map((r, i) => (
                  <tr key={i}>
                    <td>{r.name}</td>
                    <td><strong>₹{Number(r.amount).toLocaleString("en-IN")}</strong></td>
                    <td>{r.date}</td>
                    <td style={{fontSize:12}}>{r.purpose || "—"}</td>
                    <td><code style={{fontSize:11}}>{r.refId}</code></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── EXPENSE TRACKER ──────────────────────────────────────────────────────────
function ExpenseTracker({ token, members, currentUser }) {
  const empty = { category:"", subCategory:"", amount:"", mode:"Cash", chequeNo:"", bank:"", chequeDate:today(), withdrawnBy:"", spentBy:"", withdrawalRefId:"", notes:"", expenseDate:today() };
  const [form, setForm] = useState(empty);
  const [invoiceBlob, setInvoiceBlob] = useState(null);
  const [invoicePreview, setInvoicePreview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [msg, setMsg] = useState(null);
  const [records, setRecords] = useState([]);
  const [withdrawals, setWithdrawals] = useState([]);

  function set(k, v) { setForm(f => ({ ...f, [k]: v })); }

  const CATEGORIES = {
    "Utility Bills":       ["Electricity Bill","Water Bill","Pipeline Charges"],
    "AMC / Contracts":     ["Lift AMC","Generator AMC","CCTV AMC","Fire Safety AMC","Pest Control"],
    "Salaries":            ["Security Guard Salary","Housekeeping Salary","Watchman Salary","Supervisor Salary"],
    "Water Supply":        ["Tanker Charges","Water Pump Maintenance"],
    "Repairs & Maintenance":["Electrical Repairs","Plumbing","Civil Work","Painting","Common Area Repair"],
    "Administrative":      ["Printing & Stationery","Postage / Courier","Legal / Audit Fees","Bank Charges","Insurance"],
    "Horticulture":        ["Garden Maintenance","Plants & Compost","Equipment"],
    "Other":               ["Miscellaneous","Festival / Events","Emergency Expense"],
  };
  const BANKS = ["State Bank of India","Bank of Maharashtra","HDFC Bank","ICICI Bank","Axis Bank","Punjab National Bank","Canara Bank","Union Bank","Bank of Baroda","Kotak Mahindra Bank","Other"];

  useEffect(() => {
    if (!token) return;
    readSheet(SHEETS.WITHDRAWALS, token).then(setWithdrawals).catch(() => {});
  }, [token]);

  function fillWithdrawal(refId) {
    set("withdrawalRefId", refId);
    const row = withdrawals.find(r => r[6] === refId);
    if (row) set("withdrawnBy", row[1]);
  }

  async function handleSubmit() {
    if (!form.category || !form.subCategory || !form.amount) { setMsg({ type: "error", text: "Category, sub-category and amount are required." }); return; }
    if (form.mode === "Cheque" && (!form.chequeNo || !form.bank)) { setMsg({ type: "error", text: "Cheque number and bank are required for cheque payments." }); return; }
    if (!token) { setMsg({ type: "error", text: "Please sign in first." }); return; }
    setLoading(true); setMsg(null);
    try {
      let invoiceLink = "";
      if (invoiceBlob) {
        const fname = `Invoice_${form.subCategory.replace(/\s+/g,"_")}_${Date.now()}.jpg`;
        invoiceLink = await uploadToDrive(invoiceBlob, fname, token);
      }
      await appendToSheet(SHEETS.EXPENSES, [nowTs(), form.category, form.subCategory, form.amount, form.mode, form.chequeNo, form.bank, form.chequeDate, form.withdrawnBy, form.spentBy, form.withdrawalRefId, invoiceLink, form.notes, currentUser], token);
      setRecords(r => [{ ...form, invoiceLink }, ...r.slice(0, 4)]);
      setMsg({ type: "success", text: `Expense saved: ₹${Number(form.amount).toLocaleString("en-IN")} for ${form.subCategory}` });
      setForm(empty); setInvoiceBlob(null); setInvoicePreview(null);
    } catch (e) { setMsg({ type: "error", text: "Error: " + e.message }); }
    setLoading(false);
  }

  return (
    <div>
      <div className="page-title">📊 Expense Tracker</div>
      <div className="page-desc">Log all society expenses with invoice capture — utility bills, salaries, repairs, and more.</div>
      <div className="alert alert-warn" style={{ marginBottom: 18 }}>
        <span>⚠️</span>
        <span><strong>Committee members only</strong> appear in Spent By and Withdrawn By dropdowns. Cash expenses must be linked to a registered committee member.</span>
      </div>
      {msg && <Alert type={msg.type} onClose={() => setMsg(null)}>{msg.text}</Alert>}

      <div className="card">
        <div className="card-title">📂 Expense Details</div>
        <div className="form-grid">
          <div className="field">
            <label>Category *</label>
            <select value={form.category} onChange={e => { set("category", e.target.value); set("subCategory", ""); }}>
              <option value="">— Select Category —</option>
              {Object.keys(CATEGORIES).map(c => <option key={c} value={c}>{c}</option>)}
            </select>
          </div>
          <div className="field">
            <label>Sub-Category / Description *</label>
            <select value={form.subCategory} onChange={e => set("subCategory", e.target.value)} disabled={!form.category}>
              <option value="">— Select —</option>
              {(CATEGORIES[form.category] || []).map(s => <option key={s} value={s}>{s}</option>)}
            </select>
          </div>
          <div className="field">
            <label>Amount (₹) *</label>
            <input type="number" value={form.amount} onChange={e => set("amount", e.target.value)} placeholder="0.00" min="0" />
          </div>
          <div className="field">
            <label>Expense Date</label>
            <input type="date" value={form.expenseDate} onChange={e => set("expenseDate", e.target.value)} />
          </div>
          <div className="field full">
            <label>Notes / Remarks</label>
            <textarea rows={2} value={form.notes} onChange={e => set("notes", e.target.value)} placeholder="Any additional details about this expense…" style={{resize:"vertical"}} />
          </div>
        </div>
      </div>

      <div className="card">
        <div className="card-title">💳 Payment Mode</div>
        <div style={{ display:"flex", gap:12, marginBottom:18 }}>
          <button className={`btn btn-mode ${form.mode === "Cash" ? "active-cash" : "btn-secondary"}`} onClick={() => set("mode", "Cash")}>💵 Cash</button>
          <button className={`btn btn-mode ${form.mode === "Cheque" ? "active-cheque" : "btn-secondary"}`} onClick={() => set("mode", "Cheque")}>🏦 Cheque</button>
        </div>

        {form.mode === "Cheque" && (
          <div className="form-grid">
            <div className="field">
              <label>Cheque Number *</label>
              <input value={form.chequeNo} onChange={e => set("chequeNo", e.target.value)} placeholder="000456" />
            </div>
            <div className="field">
              <label>Bank *</label>
              <select value={form.bank} onChange={e => set("bank", e.target.value)}>
                <option value="">— Select Bank —</option>
                {BANKS.map(b => <option key={b} value={b}>{b}</option>)}
              </select>
            </div>
            <div className="field">
              <label>Cheque Date</label>
              <input type="date" value={form.chequeDate} onChange={e => set("chequeDate", e.target.value)} />
            </div>
          </div>
        )}

        {form.mode === "Cash" && (
          <div className="form-grid">
            <div className="field">
              <label>Spent By (Member) *</label>
              <select value={form.spentBy} onChange={e => set("spentBy", e.target.value)}>
                <option value="">— Who spent this cash? —</option>
                {members.map((m, i) => <option key={i} value={m[2]}>{m[2]}</option>)}
              </select>
            </div>
            <div className="field">
              <label>Link to Cash Withdrawal</label>
              <select value={form.withdrawalRefId} onChange={e => fillWithdrawal(e.target.value)}>
                <option value="">— Select Withdrawal Reference —</option>
                {withdrawals.map((w, i) => (
                  <option key={i} value={w[6]}>{w[6]} — {w[1]} — ₹{Number(w[2]).toLocaleString("en-IN")} ({w[3]})</option>
                ))}
              </select>
            </div>
            {form.withdrawnBy && (
              <div className="field">
                <label>Cash Originally Withdrawn By</label>
                <input value={form.withdrawnBy} readOnly />
              </div>
            )}
          </div>
        )}
      </div>

      <div className="card">
        <div className="card-title">🧾 Invoice / Bill Copy</div>
        <ImageCapture
          label="Photograph or upload the invoice / bill (compressed & saved to Google Drive)"
          preview={invoicePreview}
          onCapture={(b, u) => { setInvoiceBlob(b); setInvoicePreview(u); }}
        />
        <div className="form-actions">
          <button className="btn btn-secondary" onClick={() => { setForm(empty); setInvoiceBlob(null); setInvoicePreview(null); setMsg(null); }}>Clear</button>
          <button className="btn btn-primary" onClick={handleSubmit} disabled={loading}>
            {loading ? <><span className="spinner" /> Saving…</> : "💾 Save Expense"}
          </button>
        </div>
      </div>

      {records.length > 0 && (
        <div className="card">
          <div className="card-title">🕐 Recently Added (this session)</div>
          <div style={{ overflowX: "auto" }}>
            <table className="records-table">
              <thead><tr><th>Category</th><th>Description</th><th>Amount</th><th>Mode</th><th>Date</th></tr></thead>
              <tbody>
                {records.map((r, i) => (
                  <tr key={i}>
                    <td style={{fontSize:12}}>{r.category}</td><td>{r.subCategory}</td>
                    <td><strong>₹{Number(r.amount).toLocaleString("en-IN")}</strong></td>
                    <td><span className={`tag tag-${r.mode === "Cheque" ? "cheque" : "cash"}`}>{r.mode}</span></td>
                    <td>{r.expenseDate}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── MEMBERS TAB ─────────────────────────────────────────────────────────────
function MembersTab({ token, members, onRefresh, currentUser }) {
  const empty = { flat:"", wing:"", name:"", mobile:"", email:"" };
  const [form, setForm] = useState(empty);
  const [loading, setLoading] = useState(false);
  const [msg, setMsg] = useState(null);
  function set(k, v) { setForm(f => ({ ...f, [k]: v })); }
  const WINGS = ["A","B","C","D","E","F"];

  async function handleAdd() {
    if (!form.flat || !form.wing || !form.name) { setMsg({ type:"error", text:"Flat no, wing and name are required." }); return; }
    if (!token) { setMsg({ type:"error", text:"Please sign in first." }); return; }
    setLoading(true);
    try {
      await appendToSheet(SHEETS.MEMBERS, [form.flat, form.wing, form.name, form.mobile, form.email, "Yes"], token);
      setMsg({ type:"success", text:`${form.name} (Wing ${form.wing}, Flat ${form.flat}) added.` });
      setForm(empty); onRefresh();
    } catch (e) { setMsg({ type:"error", text:e.message }); }
    setLoading(false);
  }

  return (
    <div>
      <div className="page-title">👥 Committee Members</div>
      <div className="page-desc">Manage committee members who are authorised for cash withdrawals and expense entries. These names appear in Cash Out and Expense dropdowns.</div>
      {msg && <Alert type={msg.type} onClose={() => setMsg(null)}>{msg.text}</Alert>}

      <div className="card">
        <div className="card-title">➕ Add New Member</div>
        <div className="form-grid">
          <div className="field">
            <label>Wing *</label>
            <select value={form.wing} onChange={e => set("wing", e.target.value)}>
              <option value="">— Wing —</option>
              {WINGS.map(w => <option key={w} value={w}>Wing {w}</option>)}
            </select>
          </div>
          <div className="field">
            <label>Flat Number *</label>
            <input value={form.flat} onChange={e => set("flat", e.target.value)} placeholder="e.g. 101" />
          </div>
          <div className="field">
            <label>Committee Member Name *</label>
            <input value={form.name} onChange={e => set("name", e.target.value)} placeholder="Full name of committee member" />
          </div>
          <div className="field">
            <label>Mobile Number</label>
            <input value={form.mobile} onChange={e => set("mobile", e.target.value)} placeholder="10-digit" />
          </div>
          <div className="field">
            <label>Email (optional)</label>
            <input type="email" value={form.email} onChange={e => set("email", e.target.value)} placeholder="email@example.com" />
          </div>
        </div>
        <div className="form-actions">
          <button className="btn btn-primary" onClick={handleAdd} disabled={loading}>
            {loading ? <><span className="spinner" /> Adding…</> : "➕ Add Member"}
          </button>
        </div>
      </div>

      <div className="card">
        <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:14 }}>
          <div className="card-title" style={{ margin:0, border:0, padding:0 }}>📋 Current Members ({members.length})</div>
          <button className="btn btn-secondary" style={{ fontSize:12, padding:"6px 14px" }} onClick={onRefresh}>🔄 Refresh</button>
        </div>
        {members.length === 0
          ? <Alert type="info">No members found. Add members above, or check your Members sheet has data in rows 2+.</Alert>
          : <div style={{ overflowX:"auto" }}>
              <table className="records-table">
                <thead><tr><th>Flat</th><th>Wing</th><th>Name</th><th>Mobile</th><th>Email</th></tr></thead>
                <tbody>
                  {members.map((m, i) => (
                    <tr key={i}><td>{m[0]}</td><td>{m[1]}</td><td><strong>{m[2]}</strong></td><td>{m[3]||"—"}</td><td style={{fontSize:12}}>{m[4]||"—"}</td></tr>
                  ))}
                </tbody>
              </table>
            </div>
        }
      </div>
    </div>
  );
}

// ─── PETTY CASH TRACKER ───────────────────────────────────────────────────────
function PettyCashTracker({ token, members, currentUser }) {
  const [loading, setLoading] = useState(false);
  const [msg, setMsg] = useState(null);
  const [withdrawals, setWithdrawals] = useState([]);
  const [expenses, setExpenses] = useState([]);
  const [lastRefresh, setLastRefresh] = useState(null);

  async function loadData() {
    if (!token) { setMsg({ type: "error", text: "Please sign in first." }); return; }
    setLoading(true); setMsg(null);
    try {
      const [wd, ex] = await Promise.all([
        readSheet(SHEETS.WITHDRAWALS, token),
        readSheet(SHEETS.EXPENSES, token),
      ]);
      setWithdrawals(wd);
      setExpenses(ex.filter(r => r[4] === "Cash")); // only cash expenses
      setLastRefresh(new Date().toLocaleTimeString("en-IN"));
      setMsg({ type: "success", text: "Data refreshed successfully." });
    } catch (e) { setMsg({ type: "error", text: "Error loading data: " + e.message }); }
    setLoading(false);
  }

  useEffect(() => { loadData(); }, [token]);

  // ── Aggregations ─────────────────────────────────────────────────────────
  const totalWithdrawn = withdrawals.reduce((s, r) => s + (parseFloat(r[2]) || 0), 0);
  const totalCashSpent = expenses.reduce((s, r) => s + (parseFloat(r[3]) || 0), 0);
  const balance = totalWithdrawn - totalCashSpent;

  // Per-member: withdrawn amounts
  const wdByMember = {};
  withdrawals.forEach(r => {
    const name = r[1] || "Unknown";
    wdByMember[name] = (wdByMember[name] || 0) + (parseFloat(r[2]) || 0);
  });

  // Per-member: cash spent amounts
  const spentByMember = {};
  expenses.forEach(r => {
    const name = r[9] || r[8] || "Unknown"; // Spent By (col 9), fallback Withdrawn By (col 8)
    spentByMember[name] = (spentByMember[name] || 0) + (parseFloat(r[3]) || 0);
  });

  // All unique members involved
  const allNames = Array.from(new Set([...Object.keys(wdByMember), ...Object.keys(spentByMember)]));

  // Liability computation:
  // For each expense: if withdrawnBy ≠ spentBy, the holder (withdrawnBy) owes spentBy
  const liabilities = {}; // key: "A owes B", value: amount
  expenses.forEach(r => {
    const withdrawnBy = r[8] || "";
    const spentBy     = r[9] || "";
    const amount      = parseFloat(r[3]) || 0;
    if (withdrawnBy && spentBy && withdrawnBy !== spentBy) {
      const key = `${withdrawnBy}|||${spentBy}`;
      liabilities[key] = (liabilities[key] || 0) + amount;
    }
  });

  const liabilityRows = Object.entries(liabilities).map(([key, amt]) => {
    const [holder, creditor] = key.split("|||");
    return { holder, creditor, amt };
  });

  // Net liability (collapse A→B and B→A)
  const netLiabilities = {};
  liabilityRows.forEach(({ holder, creditor, amt }) => {
    const fwd = `${holder}|||${creditor}`;
    const rev = `${creditor}|||${holder}`;
    if (netLiabilities[rev]) {
      netLiabilities[rev] -= amt;
      if (netLiabilities[rev] < 0) {
        netLiabilities[fwd] = -netLiabilities[rev];
        delete netLiabilities[rev];
      } else if (netLiabilities[rev] === 0) {
        delete netLiabilities[rev];
      }
    } else {
      netLiabilities[fwd] = (netLiabilities[fwd] || 0) + amt;
    }
  });

  const fmt = (n) => "₹" + Math.abs(n).toLocaleString("en-IN", { minimumFractionDigits: 2 });

  async function saveSummary() {
    if (!token) return;
    try {
      await appendToSheet(SHEETS.EXPENSES.replace("Expenses","Petty_Cash_Summary"),
        [new Date().toLocaleDateString("en-IN"), totalWithdrawn, totalCashSpent, balance, currentUser], token);
      setMsg({ type: "success", text: "Summary snapshot saved to Petty_Cash_Summary sheet." });
    } catch(e) { setMsg({ type: "error", text: e.message }); }
  }

  const SummaryCard = ({ icon, label, value, color }) => (
    <div style={{ background: "#fff", borderRadius: 12, padding: "18px 20px", boxShadow: "0 2px 8px rgba(26,77,92,0.08)", borderTop: `4px solid ${color}`, flex: 1, minWidth: 160 }}>
      <div style={{ fontSize: 22, marginBottom: 6 }}>{icon}</div>
      <div style={{ fontSize: 12, fontWeight: 600, color: "#7A9199", textTransform: "uppercase", letterSpacing: "0.4px", marginBottom: 4 }}>{label}</div>
      <div style={{ fontSize: 22, fontWeight: 700, color }}>{fmt(value)}</div>
    </div>
  );

  return (
    <div>
      <div className="page-title">🏦 Petty Cash Tracker</div>
      <div className="page-desc">Full reconciliation of cash withdrawals vs. expenses. Tracks balances and cross-member liabilities.</div>

      {msg && <Alert type={msg.type} onClose={() => setMsg(null)}>{msg.text}</Alert>}

      <div style={{ display: "flex", gap: 12, marginBottom: 20, flexWrap: "wrap" }}>
        <button className="btn btn-primary" onClick={loadData} disabled={loading}>
          {loading ? <><span className="spinner" /> Loading…</> : "🔄 Refresh Data"}
        </button>
        <button className="btn btn-secondary" onClick={saveSummary} disabled={!withdrawals.length}>
          💾 Save Snapshot to Sheet
        </button>
        {lastRefresh && <span style={{ alignSelf: "center", fontSize: 12, color: "#7A9199" }}>Last updated: {lastRefresh}</span>}
      </div>

      {/* Summary Cards */}
      <div style={{ display: "flex", gap: 14, marginBottom: 20, flexWrap: "wrap" }}>
        <SummaryCard icon="⬆️" label="Total Cash Withdrawn" value={totalWithdrawn} color="#1A4D5C" />
        <SummaryCard icon="⬇️" label="Total Cash Spent" value={totalCashSpent} color="#E8871A" />
        <SummaryCard icon="💰" label="Available Balance" value={balance} color={balance >= 0 ? "#1E7E44" : "#C0392B"} />
      </div>

      {/* Per-Member Breakdown */}
      <div className="card">
        <div className="card-title">👤 Per-Member Cash Breakdown</div>
        {allNames.length === 0
          ? <Alert type="info">No cash transaction data found. Add withdrawals and cash expenses first.</Alert>
          : <div style={{ overflowX: "auto" }}>
              <table className="records-table">
                <thead>
                  <tr>
                    <th>Member</th>
                    <th>Total Withdrawn (₹)</th>
                    <th>Total Spent (₹)</th>
                    <th>Balance in Hand (₹)</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {allNames.map((name, i) => {
                    const wd  = wdByMember[name]    || 0;
                    const sp  = spentByMember[name] || 0;
                    const bal = wd - sp;
                    return (
                      <tr key={i}>
                        <td><strong>{name}</strong></td>
                        <td style={{ color: "#1A4D5C", fontWeight: 600 }}>{fmt(wd)}</td>
                        <td style={{ color: "#E8871A", fontWeight: 600 }}>{fmt(sp)}</td>
                        <td style={{ color: bal >= 0 ? "#1E7E44" : "#C0392B", fontWeight: 700 }}>{fmt(bal)}</td>
                        <td>
                          {bal > 0
                            ? <span className="tag" style={{ background: "#D4EDDA", color: "#1E7E44" }}>Has ₹{Math.abs(bal).toLocaleString("en-IN")} with them</span>
                            : bal < 0
                            ? <span className="tag" style={{ background: "#fde8e6", color: "#C0392B" }}>Overspent by ₹{Math.abs(bal).toLocaleString("en-IN")}</span>
                            : <span className="tag" style={{ background: "#EDE8E0", color: "#7A9199" }}>Settled</span>
                          }
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
        }
      </div>

      {/* Liability Table */}
      <div className="card">
        <div className="card-title">⚖️ Cross-Member Liabilities</div>
        <div style={{ fontSize: 13, color: "#7A9199", marginBottom: 14 }}>
          When Person A holds cash but Person B spends it, A owes B. Net amounts shown after cancelling mutual dues.
        </div>
        {Object.keys(netLiabilities).length === 0
          ? <Alert type="success">No outstanding liabilities — all cash holders match the spenders. ✅</Alert>
          : <div style={{ overflowX: "auto" }}>
              <table className="records-table">
                <thead>
                  <tr><th>Cash Holder (Owes)</th><th>→ To Pay</th><th>Amount</th><th>Action</th></tr>
                </thead>
                <tbody>
                  {Object.entries(netLiabilities).map(([key, amt], i) => {
                    const [holder, creditor] = key.split("|||");
                    return (
                      <tr key={i}>
                        <td><strong style={{ color: "#C0392B" }}>{holder}</strong></td>
                        <td><strong style={{ color: "#1E7E44" }}>{creditor}</strong></td>
                        <td><span style={{ fontWeight: 700, fontSize: 15, color: "#C0392B" }}>{fmt(amt)}</span></td>
                        <td><span className="tag" style={{ background: "#fff3e0", color: "#b45309" }}>Pending Settlement</span></td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
        }
      </div>

      {/* Withdrawal Detail Log */}
      <div className="card">
        <div className="card-title">📋 All Cash Withdrawals</div>
        {withdrawals.length === 0
          ? <Alert type="info">No withdrawal records found.</Alert>
          : <div style={{ overflowX: "auto" }}>
              <table className="records-table">
                <thead><tr><th>Date</th><th>Member</th><th>Amount</th><th>Purpose</th><th>Ref ID</th></tr></thead>
                <tbody>
                  {withdrawals.map((r, i) => (
                    <tr key={i}>
                      <td>{r[3]}</td>
                      <td><strong>{r[1]}</strong></td>
                      <td><strong>₹{Number(r[2]).toLocaleString("en-IN")}</strong></td>
                      <td style={{ fontSize: 12 }}>{r[4] || "—"}</td>
                      <td><code style={{ fontSize: 11 }}>{r[6] || "—"}</code></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
        }
      </div>

      {/* Cash Expense Detail Log */}
      <div className="card">
        <div className="card-title">📋 All Cash Expenses</div>
        {expenses.length === 0
          ? <Alert type="info">No cash expense records found.</Alert>
          : <div style={{ overflowX: "auto" }}>
              <table className="records-table">
                <thead>
                  <tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th><th>Withdrawn By</th><th>Spent By</th></tr>
                </thead>
                <tbody>
                  {expenses.map((r, i) => (
                    <tr key={i}>
                      <td>{r[0] ? r[0].split(",")[0] : "—"}</td>
                      <td style={{ fontSize: 12 }}>{r[1]}</td>
                      <td>{r[2]}</td>
                      <td><strong>₹{Number(r[3]).toLocaleString("en-IN")}</strong></td>
                      <td style={{ color: r[8] !== r[9] ? "#C0392B" : "#3D4F56" }}>{r[8] || "—"}</td>
                      <td style={{ color: r[8] !== r[9] ? "#1E7E44" : "#3D4F56" }}>{r[9] || "—"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
        }
      </div>
    </div>
  );
}

// ─── VIEW RECORDS ─────────────────────────────────────────────────────────────
function ViewRecords({ token }) {
  const [activeSheet, setActiveSheet] = useState("Cheque_Payments");
  const [rows, setRows] = useState([]);
  const [headers, setHeaders] = useState([]);
  const [loading, setLoading] = useState(false);
  const [msg, setMsg] = useState(null);
  const [search, setSearch] = useState("");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");

  const VIEWABLE = [
    { id: "Cheque_Payments",  label: "Cheque Payments",  icon: "🏦" },
    { id: "Cash_Withdrawals", label: "Cash Withdrawals", icon: "💵" },
    { id: "Expenses",         label: "Expenses",         icon: "📊" },
  ];

  async function loadRecords(sheet = activeSheet) {
    if (!token) { setMsg({ type: "error", text: "Please sign in first." }); return; }
    setLoading(true); setMsg(null); setRows([]); setHeaders([]);
    try {
      // Read header row
      const hUrl = `https://sheets.googleapis.com/v4/spreadsheets/${CONFIG.SPREADSHEET_ID}/values/${encodeURIComponent(sheet + "!A1:Z1")}`;
      const hResp = await fetch(hUrl, { headers: { Authorization: `Bearer ${token}` } });
      const hData = await hResp.json();
      const hdrs = (hData.values || [[]])[0] || [];
      setHeaders(hdrs);
      // Read data rows
      const data = await readSheet(sheet, token);
      setRows(data);
      if (data.length === 0) setMsg({ type: "info", text: "No records found in this sheet yet." });
    } catch (e) { setMsg({ type: "error", text: "Error: " + e.message }); }
    setLoading(false);
  }

  useEffect(() => { loadRecords(activeSheet); }, [activeSheet, token]);

  // Filter rows
  const filtered = rows.filter(r => {
    const rowText = r.join(" ").toLowerCase();
    const matchSearch = !search || rowText.includes(search.toLowerCase());
    // Date filter: col 0 is timestamp for Cheque/Expenses, col 3 is date for Withdrawals
    const dateCol = activeSheet === "Cash_Withdrawals" ? r[3] : r[0];
    const matchFrom = !dateFrom || (dateCol && dateCol >= dateFrom);
    const matchTo   = !dateTo   || (dateCol && dateCol <= dateTo + "z");
    return matchSearch && matchFrom && matchTo;
  });

  const totalAmount = filtered.reduce((s, r) => {
    const amtIdx = headers.findIndex(h => h.toLowerCase() === "amount");
    return s + (amtIdx >= 0 ? parseFloat(r[amtIdx]) || 0 : 0);
  }, 0);

  function downloadCSV() {
    const csvRows = [headers, ...filtered].map(r => r.map(c => `"${(c||"").replace(/"/g,'""')}"`).join(","));
    const blob = new Blob([csvRows.join("\n")], { type: "text/csv" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `${activeSheet}_${today()}.csv`;
    a.click();
  }

  return (
    <div>
      <div className="page-title">📁 View Records</div>
      <div className="page-desc">Browse, search, and filter all recorded data from your Google Sheets.</div>

      {msg && <Alert type={msg.type} onClose={() => setMsg(null)}>{msg.text}</Alert>}

      {/* Sheet Selector */}
      <div style={{ display: "flex", gap: 10, marginBottom: 20, flexWrap: "wrap" }}>
        {VIEWABLE.map(s => (
          <button key={s.id}
            className={`btn ${activeSheet === s.id ? "btn-primary" : "btn-secondary"}`}
            onClick={() => { setActiveSheet(s.id); setSearch(""); setDateFrom(""); setDateTo(""); }}>
            {s.icon} {s.label}
          </button>
        ))}
      </div>

      {/* Filters */}
      <div className="card" style={{ padding: "16px 20px" }}>
        <div style={{ display: "flex", gap: 12, flexWrap: "wrap", alignItems: "flex-end" }}>
          <div className="field" style={{ flex: 2, minWidth: 180 }}>
            <label>🔍 Search</label>
            <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Name, cheque no, category…" />
          </div>
          <div className="field" style={{ minWidth: 140 }}>
            <label>From Date</label>
            <input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)} />
          </div>
          <div className="field" style={{ minWidth: 140 }}>
            <label>To Date</label>
            <input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)} />
          </div>
          <button className="btn btn-secondary" onClick={() => { setSearch(""); setDateFrom(""); setDateTo(""); }}>Clear</button>
          <button className="btn btn-secondary" onClick={() => loadRecords()} disabled={loading}>
            {loading ? <><span className="spinner" style={{ borderTopColor: "#3D4F56", borderColor: "#ccc" }} /> Loading</> : "🔄 Refresh"}
          </button>
          {filtered.length > 0 && (
            <button className="btn btn-secondary" onClick={downloadCSV}>⬇️ CSV</button>
          )}
        </div>
      </div>

      {/* Stats bar */}
      {filtered.length > 0 && (
        <div style={{ display: "flex", gap: 16, marginBottom: 14, flexWrap: "wrap" }}>
          <div style={{ fontSize: 13, color: "#7A9199" }}>
            Showing <strong style={{ color: "#1A4D5C" }}>{filtered.length}</strong> of {rows.length} records
          </div>
          {totalAmount > 0 && (
            <div style={{ fontSize: 13, color: "#7A9199" }}>
              Total Amount: <strong style={{ color: "#1A4D5C" }}>₹{totalAmount.toLocaleString("en-IN", { minimumFractionDigits: 2 })}</strong>
            </div>
          )}
        </div>
      )}

      {/* Data Table */}
      <div className="card" style={{ padding: "0", overflow: "hidden" }}>
        {loading
          ? <div style={{ padding: 40, textAlign: "center", color: "#7A9199" }}>
              <div style={{ fontSize: 32, marginBottom: 10 }}>⏳</div>
              Loading records…
            </div>
          : filtered.length === 0
          ? <div style={{ padding: 30, textAlign: "center" }}>
              <div style={{ fontSize: 32, marginBottom: 8 }}>📭</div>
              <div style={{ color: "#7A9199", fontSize: 14 }}>No records match your filters.</div>
            </div>
          : <div style={{ overflowX: "auto" }}>
              <table className="records-table">
                <thead>
                  <tr>{headers.map((h, i) => <th key={i}>{h}</th>)}</tr>
                </thead>
                <tbody>
                  {filtered.map((row, ri) => (
                    <tr key={ri}>
                      {headers.map((h, ci) => {
                        const val = row[ci] || "";
                        const isLink = val.startsWith("http");
                        const isAmt  = h.toLowerCase() === "amount";
                        const isMode = h === "Payment Mode";
                        return (
                          <td key={ci} style={{ fontSize: 12, maxWidth: 180, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                            {isLink
                              ? <a href={val} target="_blank" rel="noreferrer" style={{ color: "#3A8FA3", textDecoration: "underline" }}>🔗 View</a>
                              : isAmt
                              ? <strong>₹{Number(val).toLocaleString("en-IN")}</strong>
                              : isMode
                              ? <span className={`tag tag-${val === "Cheque" ? "cheque" : "cash"}`}>{val}</span>
                              : val || "—"
                            }
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
        }
      </div>
    </div>
  );
}

// ─── MAIN APP ─────────────────────────────────────────────────────────────────
// Setup tab hidden from nav — accessible only when needed via setTab("setup")
const TABS = [
  { id:"members",    label:"Committee",   icon:"👥" },
  { id:"cheque",     label:"Cheques",     icon:"🏦" },
  { id:"withdrawal", label:"Cash Out",    icon:"💵" },
  { id:"expense",    label:"Expenses",    icon:"📊" },
  { id:"petty",      label:"Cash Tracker",icon:"⚖️" },
  { id:"records",    label:"View Records",icon:"📁" },
];

export default function App() {
  const [tab, setTab] = useState("members");
  const [token, setToken] = useState(null);
  const [currentUser, setCurrentUser] = useState("");
  const [members, setMembers] = useState([]);
  const [authLoading, setAuthLoading] = useState(false);

  useEffect(() => {
    const s = document.createElement("script");
    s.src = "https://accounts.google.com/gsi/client";
    s.async = true;
    document.head.appendChild(s);
    return () => { try { document.head.removeChild(s); } catch(e){} };
  }, []);

  function signIn() {
    if (!window.google) { alert("Google SDK loading… please try again in a moment."); return; }
    setAuthLoading(true);
    const client = window.google.accounts.oauth2.initTokenClient({
      client_id: CONFIG.CLIENT_ID,
      scope: CONFIG.SCOPES,
      callback: async (resp) => {
        if (resp.error) { setAuthLoading(false); return; }
        setToken(resp.access_token);
        try {
          const r = await fetch("https://www.googleapis.com/oauth2/v3/userinfo", { headers: { Authorization: `Bearer ${resp.access_token}` } });
          const u = await r.json();
          setCurrentUser(u.name || u.email || "User");
          const rows = await readSheet(SHEETS.MEMBERS, resp.access_token);
          setMembers(rows);
        } catch(e){}
        setAuthLoading(false);
      },
    });
    client.requestAccessToken();
  }

  function signOut() { setToken(null); setCurrentUser(""); setMembers([]); }

  const isConfigured = CONFIG.SPREADSHEET_ID !== "YOUR_SPREADSHEET_ID_HERE";
  const refreshMembers = (t = token) => readSheet(SHEETS.MEMBERS, t).then(setMembers).catch(()=>{});

  return (
    <>
      <style>{globalCSS}</style>
      <header className="portal-header">
        <div className="header-top">
          <div className="header-logo">🏢</div>
          <div>
            <div className="header-title">Shubh Nisarg CHS Ltd</div>
            <div className="header-sub">Society Management Portal · Badlapur, Thane, Maharashtra</div>
          </div>
          <div className="header-auth">
            {token
              ? <>
                  <span className="auth-badge">👤 {currentUser}</span>
                  <button className="btn-auth" onClick={signOut}>Sign Out</button>
                </>
              : <button className="btn-auth" onClick={signIn} disabled={authLoading || !isConfigured}>
                  {authLoading ? "Signing in…" : "🔐 Sign in with Google"}
                </button>
            }
          </div>
        </div>
        <nav className="nav-tabs">
          {TABS.map(t => (
            <button key={t.id} className={`nav-tab ${tab === t.id ? "active" : ""}`} onClick={() => setTab(t.id)}>
              {t.icon} {t.label}
            </button>
          ))}
        </nav>
      </header>

      <main className="page">
        {!token && (
          <Alert type="warn">Please sign in with Google to use this portal.</Alert>
        )}
        {tab === "setup"      && <SetupGuide token={token} onHeadersWritten={() => refreshMembers()} />}
        {tab === "members"    && <MembersTab token={token} members={members} onRefresh={refreshMembers} currentUser={currentUser} />}
        {tab === "cheque"     && <ChequePayment token={token} currentUser={currentUser} />}
        {tab === "withdrawal" && <CashWithdrawal token={token} members={members} currentUser={currentUser} />}
        {tab === "expense"    && <ExpenseTracker token={token} members={members} currentUser={currentUser} />}
        {tab === "petty"      && <PettyCashTracker token={token} members={members} currentUser={currentUser} />}
        {tab === "records"    && <ViewRecords token={token} />}
      </main>
    </>
  );
}
